### ISSUE TITLE
Miss devDependencies '@types/node'

### ISSUE THREAD

**Issue by winnyWan** [sj-distributor/create-react-boilerplates#52]
step:
- pnpm create react-boilerplates
- pnpm install

In vite.config.ts file:
![image](https://github.com/sj-distributor/create-react-boilerplates/assets/126317306/9446ff2e-e4c2-43da-9d19-e7a0382293cc)

![image](https://github.com/sj-distributor/create-react-boilerplates/assets/126317306/705a6314-4039-4300-995c-969f15f7c7d7)

**Comment by Simoon-F** [comment]
ACK.
